# Docker Compose para el proyecto .NET
version: '3.8'

services:
  # Servicio de la aplicación .NET
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./core.net_service/appsettings.json:/app/appsettings.json:ro
    depends_on:
      - postgres
    networks:
      - app-network

  # Servicio de PostgreSQL (opcional, si quieres usar una BD local)
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: operaciones_aritmeticas
      POSTGRES_USER: arturo_eg
      POSTGRES_PASSWORD: local_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
