version: '3.8'

services:
  # Servicio de la aplicación .NET
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./core.net_service/appsettings.json:/app/appsettings.json:ro
    depends_on:
      - postgres
    networks:
      - app-network
    entrypoint: [ "./wait-for-it.sh", "postgres:5432", "--", "dotnet", "core.net_service.dll" ]

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: operaciones_aritmeticas
      POSTGRES_USER: arturo_eg
      POSTGRES_PASSWORD: Wg95cHgE0evEfassMjwg8SQPiSlMPXR1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data: {}

networks:
  app-network:
    driver: bridge
